---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml --ask-vault-pass

- hosts: all  # should be limited to database-servers
  become: yes
  gather_facts: yes
  roles:
    - ansibleguy.infra_mariadb
