---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

collections:
  - name: 'community.mysql'
    source: 'https://galaxy.ansible.com'

  - name: 'ansible.posix'
    source: 'https://galaxy.ansible.com'
