---

- name: Converge
  hosts: all
  vars:
    no_prompts: true  # mariadb prompts

    mariadb:
      instances:
        test1:
          dbs:
            db1:
              'encoding': 'utf8mb4'
              'collation': 'utf8mb4_general_ci'
          users:
            user1:
              priv: 'db1.*:ALL'
              pwd: 'random'
          settings:
            innodb_log_file_size: '256M'
            wait_timeout: 600
            transaction-isolation: 'READ-COMMITTED'
            binlog_format: 'ROW'

        test2:
          dbs:
            db1:
            db2:
          users:
            user1:
              pwd: 'random2'
            user2:
              pwd: 'random3'

  roles:
    - ansibleguy.infra_mariadb
