---

- name: "MariaDB | Remove Instance '{{ name }}' | Ask user"
  ansible.builtin.pause:
    prompt: "Do you really want to remove the database instance '{{ name }}' and all of its data? Do you want to try to dump its data before removing it? [yes/NO]!"
  register: removal_prompt
  when: not force_removal

- name: "MariaDB | Remove Instance '{{ name }}' | Dumping database data before removing it"
  community.mysql.mysql_db:
    state: 'dump'
    name: all
    target: "{{ path_backup }}/{{ name }}_{{ ansible_date_time.iso8601_basic_short }}_pre-removal.sql.xz"
    login_unix_socket: "{{ socket }}"
    login_user: "{{ instance.ansible_user }}"
    login_password: "{{ instance | mgmt_pwd }}"
    use_shell: true
  when:
    - not force_removal
    - removal_prompt.user_input == 'yes'
  register: removal_dump
  ignore_errors: true  # if the db service is already stopped..

- name: "MariaDB | Remove Instance '{{ name }}' | Dump info"
  ansible.builtin.debug:
    msg: "Dumped database to: '{{ path_backup }}/{{ name }}_{{ ansible_date_time.iso8601_basic_short }}_pre-removal.sql.xz'"
  when:
    - not force_removal
    - removal_dump is defined
    - removal_dump.failed is undefined or not removal_dump.failed

- name: "MariaDB | Remove Instance '{{ name }}' | Ask user if we should continue"
  ansible.builtin.pause:
    prompt: 'It seems that we are not able to dump the data of this instance! Do you still want to continue? (not recommended) [yes/NO]'
  register: removal_dump_prompt
  when:
    - not force_removal
    - removal_dump is defined
    - removal_dump.failed is defined
    - removal_dump.failed

- name: "MariaDB | Remove Instance '{{ name }}' | Removing/Disabling instance service"
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "mariadb@{{ name }}.service"
    enabled: no
    state: stopped
  when: >
    removal_dump_prompt.user_input is undefined or
    removal_dump_prompt.user_input == 'yes'
  register: mariadb_instance_removal
  failed_when:
    - mariadb_instance_removal.failed
    - "'does not exist' not in mariadb_instance_removal.msg"
    - "'Could not find' not in mariadb_instance_removal.msg"


- name: "MariaDB | Remove Instance '{{ name }}' | Removing/Disabling backup timer"
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ backup.service_prefix }}backup-mariadb-{{ name }}.timer"
    enabled: no
    state: stopped
  when: >
    removal_dump_prompt.user_input is undefined or
    removal_dump_prompt.user_input == 'yes'
  register: mariadb_backup_removal
  failed_when:
    - mariadb_backup_removal.failed
    - "'does not exist' not in mariadb_backup_removal.msg"
    - "'Could not find' not in mariadb_backup_removal.msg"

# we'll leave the backup-path as-is
- name: "MariaDB | Remove Instance '{{ name }}' | Removing files/directories"
  ansible.builtin.file:
    path: "{{ MARIADB_CONFIG.config.path_ssl }}/{{ name }}"
    state: absent
    force: yes
  loop:
    - "{{ path_data }}"
    - "{{ MARIADB_CONFIG.config.path_config }}/server_{{ name }}.cnf"
    - "{{ MARIADB_CONFIG.config.path_config }}/client_{{ name }}_startup-checks.cnf"
    - "{{ MARIADB_CONFIG.config.path_config }}/client_{{ name }}_backup.cnf"
    - "/etc/systemd/system/{{ backup.service_prefix }}backup-mariadb-{{ name }}.service"
    - "/etc/systemd/system/{{ backup.service_prefix }}backup-mariadb-{{ name }}.timer"
  when: >
    removal_dump_prompt.user_input is undefined or
    removal_dump_prompt.user_input == 'yes'
